<a href="https://colab.research.google.com/github/Amith567/Numpy_Tutorial/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy
import numpy as np

In [ ]:
a=np.array([[2,3,4],[3,4,5]],dtype=float)
print(a,a.shape)
print(type(a))
print(a.ndim)
print(a.size)
b=a.astype(float)
print(b)

[[2. 3. 4.]
 [3. 4. 5.]] (2, 3)
<class 'numpy.ndarray'>
2
6
[[2. 3. 4.]
 [3. 4. 5.]]


In [ ]:
a=np.zeros((2,10),dtype=int,order='F')
print(a)
a=np.ones((10,5),dtype=int,order='F')
print(a)
a=np.full((10,3),5,dtype=int)
print(a)
a=np.arange(6)
print(a)
a=np.linspace(10,15,15,endpoint=True,dtype=int)
print(a,a.size)
a=np.eye(10,10,-3)
print(a)
a=np.random.rand(2,4)
print(a)
a=np.random.randn(2,4)
print(a,a.sum(),a.mean())
a=np.random.randint(1,10,(3,4))
print(a)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]
[0 1 2 3 4 5]
[10 10 10 11 11 11 12 12 12 13 13 13 14 14 15] 15
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
[[0.31722085 0.90641614 0.21461993 0.40084794]
 [0.35211195 0.84217801 0.53838495 0.33805784]]
[[-1.19691441 -0.60219463 -0.2351228  -1.10587273]
 [ 1.39531156  0.76815001  0.80873155  0.41090804]] 0.24299658846178307 0.030374573557722884
[[9 5 6 8]
 [2 7 5 9]
 [4 9 4 7]]


In [ ]:
a=np.array([[1,2,3,4],[3,4,5,6],[3,2,1,4]])
print(a,a.shape,a.size)
print(a[a>10])

[[1 2 3 4]
 [3 4 5 6]
 [3 2 1 4]] (3, 4) 12


In [ ]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a+b)
print(a-b)
print(a*b)
print(a/2)
print(a>2)
print(np.sqrt(a))
print(np.square(a))

In [ ]:
a=np.array([1,2,3])
b=np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3]])
print(a.shape,b.shape)
print(a+b)

(3,) (4, 3)
[[2 4 6]
 [2 4 6]
 [2 4 6]
 [2 4 6]]


In [ ]:
a=np.array([[2,3,4,4],[3,5,3,5]])
print(a.reshape(2,2))
print(a.flatten(order='F'))
b=a.ravel()
print(b,b.shape)
print(a.T)
print(np.transpose(a))
print(a.shape)
print(np.expand_dims(a,axis=0))
print(np.squeeze(a,axis=None))


(2, 4)
[[[2 3 4 4]
  [3 5 3 5]]]


In [ ]:
a=np.array([1,2,9,3,4,5])
print(a.sum(),a.mean(),a.min(),a.max())
print(a.std(),a.var(),a.argmin(),a.argmax())

24 4.0 1 9
2.581988897471611 6.666666666666667 0 2


In [ ]:
a=np.array([[1,2],[2,1]])
b=np.array([[2,3,2],[3,2,2]])
print((a@b).shape)
print(np.matmul(a,b).shape)
print(np.dot(a,b).shape)
a=np.array([[1,2],[2,1]])
print(np.linalg.inv(a))
print(np.linalg.det(a))
print(np.linalg.eig(a))

(2, 3)
(2, 3)
(2, 3)


In [ ]:
a=np.array([[1,2,3,4],[1,2,3,4]])
print(np.split(a,2))
print(np.concatenate((a,a)))
print(np.hsplit(a,2))
print(np.vsplit(a,2))

[array([[1, 2, 3, 4]]), array([[1, 2, 3, 4]])]


In [ ]:
np.sort()

np.argsort()

np.where()

np.unique()

TypeError: sort() missing 1 required positional argument: 'a'

In [ ]:
np.nan

np.isnan()

np.isinf()

np.nanmean(), np.nanmax()

NameError: name 'np' is not defined

In [ ]:
np.random.seed()

np.random.choice()